#!/usr/bin/env python3
"""Export trained DIA model weights to a Rust source file."""
import torch
import numpy as np
import argparse
import os


def format_array(name, values, per_line=8):
    """Format a float array as a Rust const."""
    lines = [f"pub const {name}: &[f32] = &["]
    for i in range(0, len(values), per_line):
        chunk = values[i:i+per_line]
        line = "    " + ", ".join(f"{v:.8e}" for v in chunk) + ","
        lines.append(line)
    lines.append("];")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model', type=str, default='model.pt')
    parser.add_argument('--output', type=str,
                        default='../../pancetta-ft8/src/neural_osd_weights.rs')
    args = parser.parse_args()

    # Load model
    from train import DIAModel
    model = DIAModel()
    model.load_state_dict(torch.load(args.model, map_location='cpu', weights_only=True))
    model.eval()

    # Extract weights
    weights = {}
    for name, param in model.named_parameters():
        weights[name] = param.detach().numpy().flatten().tolist()

    # Generate Rust source
    lines = [
        "// Auto-generated by training/neural_osd/export_weights.py",
        "// DO NOT EDIT — regenerate with:",
        "//   cd training/neural_osd && python export_weights.py",
        "",
        "#![allow(clippy::excessive_precision)]",
        "",
    ]

    # Conv1: weight shape (32, 25, 3), bias shape (32,)
    lines.append(format_array("CONV1_WEIGHT", weights['conv1.weight']))
    lines.append("")
    lines.append(format_array("CONV1_BIAS", weights['conv1.bias']))
    lines.append("")

    # Conv2: weight shape (16, 32, 3), bias shape (16,)
    lines.append(format_array("CONV2_WEIGHT", weights['conv2.weight']))
    lines.append("")
    lines.append(format_array("CONV2_BIAS", weights['conv2.bias']))
    lines.append("")

    # Conv3: weight shape (1, 16, 1), bias shape (1,)
    lines.append(format_array("CONV3_WEIGHT", weights['conv3.weight']))
    lines.append("")
    lines.append(format_array("CONV3_BIAS", weights['conv3.bias']))
    lines.append("")

    # Linear: weight shape (91, 174), bias shape (91,)
    lines.append(format_array("LINEAR_WEIGHT", weights['linear.weight']))
    lines.append("")
    lines.append(format_array("LINEAR_BIAS", weights['linear.bias']))

    rust_code = "\n".join(lines) + "\n"

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, 'w') as f:
        f.write(rust_code)

    total_params = sum(len(v) for v in weights.values())
    file_size = len(rust_code)
    print(f"Exported {total_params:,} parameters to {args.output}")
    print(f"File size: {file_size:,} bytes ({file_size/1024:.1f} KB)")


if __name__ == '__main__':
    main()
