//! Off-air WAV file decoding tests
//!
//! These tests decode real off-air FT8 recordings and synthetic test signals
//! from WSJT-X, JTDX, and BasicFT8 sample collections. This validates the
//! decoder against signals generated by independent FT8 implementations.

use pancetta_ft8::{Ft8Decoder, Ft8Config, DecodedMessage, WINDOW_SAMPLES, SAMPLE_RATE};

/// Read a 16-bit mono WAV file and return f32 samples.
/// Panics if the file doesn't match expected format (mono, 12 kHz, 16-bit).
fn read_wav_file(path: &str) -> Vec<f32> {
    let reader = hound::WavReader::open(path)
        .unwrap_or_else(|e| panic!("Failed to open {}: {}", path, e));

    let spec = reader.spec();
    assert_eq!(spec.channels, 1, "Expected mono, got {} channels", spec.channels);
    assert_eq!(
        spec.sample_rate, SAMPLE_RATE,
        "Expected {} Hz, got {} Hz",
        SAMPLE_RATE, spec.sample_rate
    );
    assert_eq!(
        spec.bits_per_sample, 16,
        "Expected 16-bit, got {}-bit",
        spec.bits_per_sample
    );

    reader
        .into_samples::<i16>()
        .map(|s| s.unwrap() as f32 / 32768.0)
        .collect()
}

/// Decode a WAV file and return all decoded messages.
/// Passes the full recording to the decoder so it can search across
/// all possible time offsets for FT8 signals.
fn decode_wav_file(path: &str) -> Vec<DecodedMessage> {
    let samples = read_wav_file(path);

    // Pass the full recording (>= WINDOW_SAMPLES) so the decoder
    // can search across time offsets for signals that don't start at t=0.
    let buffer: Vec<f32> = if samples.len() >= WINDOW_SAMPLES {
        samples
    } else {
        let mut padded = samples;
        padded.resize(WINDOW_SAMPLES, 0.0);
        padded
    };

    let config = Ft8Config::default();
    let mut decoder = Ft8Decoder::new(config).unwrap();
    decoder.decode_window(&buffer).unwrap_or_default()
}

/// Helper to check if any decoded message contains a specific callsign
fn has_callsign(messages: &[DecodedMessage], call: &str) -> bool {
    messages.iter().any(|m| m.text.contains(call))
}

/// Helper to print decoded messages for diagnostics
fn print_decoded(label: &str, messages: &[DecodedMessage]) {
    println!("--- {} ({} messages) ---", label, messages.len());
    for m in messages {
        println!("  [{:6.1} dB] {}", m.snr_db, m.text);
    }
}

// =============================================================
// Fixture path helper
// =============================================================

fn fixture(subpath: &str) -> String {
    format!(
        "{}/tests/fixtures/wav/{}",
        env!("CARGO_MANIFEST_DIR"),
        subpath
    )
}

// =============================================================
// JTDX samples
// =============================================================

#[test]
fn test_decode_jtdx_synthetic() {
    let path = fixture("jtdx/000000_000001.wav");
    let decoded = decode_wav_file(&path);
    print_decoded("jtdx/000000_000001.wav (synthetic)", &decoded);

    // Synthetic test signal should have at least one decodable message
    assert!(
        !decoded.is_empty(),
        "Synthetic JTDX test signal should produce at least one decoded message"
    );

    // All decoded messages should have valid FT8 message format
    for m in &decoded {
        assert!(!m.text.is_empty(), "Decoded message text should not be empty");
    }
}

#[test]
fn test_decode_jtdx_offair() {
    let path = fixture("jtdx/190227_155815.wav");
    let decoded = decode_wav_file(&path);
    print_decoded("jtdx/190227_155815.wav (off-air)", &decoded);

    // Real off-air recording should have decodable signals
    assert!(
        !decoded.is_empty(),
        "JTDX off-air recording should produce at least one decoded message"
    );
}

// =============================================================
// WSJT samples
// =============================================================

#[test]
fn test_decode_wsjt_210703() {
    let path = fixture("wsjt/210703_133430.wav");
    let decoded = decode_wav_file(&path);
    print_decoded("wsjt/210703_133430.wav", &decoded);

    assert!(
        !decoded.is_empty(),
        "WSJT off-air recording should produce at least one decoded message"
    );
}

#[test]
fn test_decode_wsjt_181201() {
    let path = fixture("wsjt/181201_180245.wav");
    let decoded = decode_wav_file(&path);
    print_decoded("wsjt/181201_180245.wav", &decoded);

    assert!(
        !decoded.is_empty(),
        "WSJT off-air recording should produce at least one decoded message"
    );
}

#[test]
fn test_decode_wsjt_170709() {
    let path = fixture("wsjt/170709_135615.wav");
    let decoded = decode_wav_file(&path);
    print_decoded("wsjt/170709_135615.wav", &decoded);

    assert!(
        !decoded.is_empty(),
        "WSJT off-air recording should produce at least one decoded message"
    );
}

// =============================================================
// BasicFT8 samples (consecutive 15s windows)
// =============================================================

#[test]
fn test_decode_basicft8_window_0() {
    let path = fixture("basicft8/170923_082000.wav");
    let decoded = decode_wav_file(&path);
    print_decoded("basicft8/170923_082000.wav", &decoded);

    assert!(
        !decoded.is_empty(),
        "BasicFT8 sample should produce at least one decoded message"
    );
}

#[test]
fn test_decode_basicft8_window_1() {
    let path = fixture("basicft8/170923_082015.wav");
    let decoded = decode_wav_file(&path);
    print_decoded("basicft8/170923_082015.wav", &decoded);

    assert!(
        !decoded.is_empty(),
        "BasicFT8 sample should produce at least one decoded message"
    );
}

#[test]
fn test_decode_basicft8_window_2() {
    let path = fixture("basicft8/170923_082030.wav");
    let decoded = decode_wav_file(&path);
    print_decoded("basicft8/170923_082030.wav", &decoded);

    assert!(
        !decoded.is_empty(),
        "BasicFT8 sample should produce at least one decoded message"
    );
}

#[test]
fn test_decode_basicft8_window_3() {
    let path = fixture("basicft8/170923_082045.wav");
    let decoded = decode_wav_file(&path);
    print_decoded("basicft8/170923_082045.wav", &decoded);

    assert!(
        !decoded.is_empty(),
        "BasicFT8 sample should produce at least one decoded message"
    );
}

// =============================================================
// Aggregate decode quality test
// =============================================================

/// Decode all 9 WAV files and report aggregate statistics.
/// At minimum, we should decode messages from at least 7 of 9 files.
#[test]
fn test_decode_aggregate_quality() {
    let files = [
        "jtdx/000000_000001.wav",
        "jtdx/190227_155815.wav",
        "wsjt/210703_133430.wav",
        "wsjt/181201_180245.wav",
        "wsjt/170709_135615.wav",
        "basicft8/170923_082000.wav",
        "basicft8/170923_082015.wav",
        "basicft8/170923_082030.wav",
        "basicft8/170923_082045.wav",
    ];

    let mut total_messages = 0;
    let mut files_with_decodes = 0;

    for file in &files {
        let decoded = decode_wav_file(&fixture(file));
        let count = decoded.len();
        total_messages += count;
        if count > 0 {
            files_with_decodes += 1;
        }
        println!("{}: {} messages", file, count);
    }

    println!(
        "\nAggregate: {} messages from {}/{} files",
        total_messages,
        files_with_decodes,
        files.len()
    );

    assert!(
        files_with_decodes >= 7,
        "Should decode messages from at least 7 of 9 WAV files, got {}/9",
        files_with_decodes
    );

    assert!(
        total_messages >= 10,
        "Should decode at least 10 total messages across all files, got {}",
        total_messages
    );
}
