name: Docs

on:
  push:
    branches: [main]
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - '.github/workflows/docs.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev libudev-dev libssl-dev pkg-config

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          key: docs

      - name: Build docs
        run: cargo doc --workspace --no-deps
        env:
          RUSTDOCFLAGS: "--default-theme ayu"

      - name: Upload docs artifact
        uses: actions/upload-artifact@v7
        with:
          name: rustdoc
          path: target/doc
          retention-days: 30
